language: go

go:
  - 1.7

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="master"
    - DEPLOY_BRANCH="gh-pages"

install:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_TOKEN}
    local_dir: public
    skip_cleanup: true
